export const configDetailsHome = {
  ALLOWED_ATTR: [
    "src",
    "width",
    "height",
    "loading",
    "referrerpolicy",
    "class",
    "id",
    "href",
    "overlay",
    "menu-toggler",
    "alt",
    "role",
    "type",
    "name",
    "allow",
    "allowfullscreen",
    "frameborder",
    "title",
    "sandbox",
    "style",
    "background",
  ],
  ALLOW_UNSAFE_SCRIPT: false,
  ALLOW_ARIA_ATTR: true,
  ALLOW_UNKNOWN_PROTOCOLS: false,
  ALLOWED_TAGS: [
    "a",
    "div",
    "span",
    "img",
    "p",
    "button",
    "input",
    "aside",
    "main",
    "iframe",
    "figure",
    "h1",
    "h2",
    "h3",
    "h4",
  ],
};
