export const configMovies = {
  ALLOWED_ATTR: [
    "src",
    "width",
    "height",
    "loading",
    "referrerpolicy",
    "class",
    "id",
    "href",
    "overlay",
    "menu-toggler",
    "alt",
    "role",
    "type",
    "name",
    "style",
  ],
  ALLOW_UNSAFE_SCRIPT: false,
  ALLOW_ARIA_ATTR: true,
  ALLOW_UNKNOWN_PROTOCOLS: false,
  ALLOWED_TAGS: [
    "a",
    "div",
    "span",
    "img",
    "header",
    "nav",
    "p",
    "button",
    "section",
    "figure",
  ],
  ALLOWED_URI_REGEXP: /^https?:\/\//,
};
